SeeSharpersCinema/Controllers/PlayListController.cs
using Microsoft.AspNetCore.Mvc;
using SeeSharpersCinema.Models.Repository;
using SeeSharpersCinema.Models.ViewModel;
using System.Linq;
using System.Threading.Tasks;

namespace SeeSharpersCinema.Controllers
{
    public class PlayListController : Controller
    {
        private IPlayListRepository repository;

        public PlayListController(IPlayListRepository repo)
        {
            repository = repo;
        }

        //public ViewResult Overview()
        //    => View(new PlayListViewModel
        //    {
        //        PlayLists = repository.PlayLists
        //        .OrderBy(p => p.TimeSlotId)
        //    });

        public async Task<IActionResult> Overview()
        {
            return View(await repository.FindAllAsync());
        }
    }
}

SeeSharpersCinema/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using SeeSharpersCinema.Models.Order;
using SeeSharpersCinema.Models.Film;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SeeSharpersCinema.Models.Repository;

namespace SeeSharpersCinema.Controllers
{
    public class TicketController : Controller
    {
        private IMovieRepository repository;
        public TicketController(IMovieRepository repository) 
        {
            this.repository = repository;
        }

        [Route("Ticket/Options/{movieId}")]
        public IActionResult Options([FromRoute] long movieId)
        {
            var selectedMovie = repository.Movies.FirstOrDefault(m => m.Id == movieId);
            if (selectedMovie == null)
            {
             return NotFound();
            } 

            Ticket ticket = new Ticket()
            {
                Movie = selectedMovie
            };
            return View(ticket);
        }

        [Route("Ticket/QR/{TicketId}")]
        public IActionResult QR(Ticket ticket)
        {
            return View(ticket);
        }
    }
}

SeeSharpersCinema/Views/Shared/MovieSummary.cshtml
@model Movie

<div class="col-3">
    <div class="card card-outline-primary m-1 p-1">
        <div class="card-text p-1">
            <a asp-controller="Ticket" asp-action="Selector" asp-route-movieId="@Model.Id">
                <img class="img-fluid" src="@Model.PosterUrl" />
            </a>
        </div>
    </div>
</div>

SeeSharpersCinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SeeSharpersCinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SeeSharpersCinema</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlayList" asp-action="Overview">PlayList</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SeeSharpersCinema - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>