SeeSharpersCinema.BackOffice/Controllers/PlayListsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeeSharpersCinema.Models.Database;
using SeeSharpersCinema.Models.Program;
using System.Linq;
using System.Threading.Tasks;

namespace SeeSharpersCinema.BackOffice.Controllers
{
    [Authorize(Roles = "Admin,BackOffice")]
    public class PlayListsController : Controller
    {
        private readonly CinemaDbContext _context;

        public PlayListsController(CinemaDbContext context)
        {
            _context = context;
        }

        // GET: PlayLists
        public async Task<IActionResult> Index()
        {
            var cinemaDbContext = _context.PlayLists.Include(p => p.Movie).Include(p => p.TimeSlot);
            return View(await cinemaDbContext.ToListAsync());
        }

        // GET: PlayLists/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playList = await _context.PlayLists
                .Include(p => p.Movie)
                .Include(p => p.TimeSlot)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (playList == null)
            {
                return NotFound();
            }

            return View(playList);
        }






        /*        public IActionResult Create()
                {
                    PopulateTimeSlotDropDownList();
                    return View();
                }
                private void PopulateTimeSlotDropDownList(object selectedDepartment = null)
                {
                    var departmentsQuery = from d in _context.TimeSlots
                                           orderby d.SlotStart
                                           select d;
                    ViewBag.TimeslotId = new SelectList(departmentsQuery.AsNoTracking(), "DepartmentID", "Name", selectedDepartment);
                }*/


        // GET: PlayLists/Create
        public IActionResult Create()
        {
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id");
            ViewData["TimeSlotId"] = new SelectList(_context.TimeSlots, "Id", "Id");
            return View();
        }

        // POST: PlayLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TimeSlotId,MovieId")] PlayList playList)

        {
            if (ModelState.IsValid)
            {
                _context.Add(playList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", playList.MovieId);
            ViewData["TimeSlotId"] = new SelectList(_context.TimeSlots, "Id", "Id", playList.TimeSlotId);
            return View(playList);
        }









        // GET: PlayLists/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playList = await _context.PlayLists.FindAsync(id);
            if (playList == null)
            {
                return NotFound();
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", playList.MovieId);
            ViewData["TimeSlotId"] = new SelectList(_context.TimeSlots, "Id", "Id", playList.TimeSlotId);
            return View(playList);
        }

        // POST: PlayLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,TimeSlotId,MovieId")] PlayList playList)
        {
            if (id != playList.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(playList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayListExists(playList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", playList.MovieId);
            ViewData["TimeSlotId"] = new SelectList(_context.TimeSlots, "Id", "Id", playList.TimeSlotId);
            return View(playList);
        }







        // GET: PlayLists/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playList = await _context.PlayLists
                .Include(p => p.Movie)
                .Include(p => p.TimeSlot)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (playList == null)
            {
                return NotFound();
            }

            return View(playList);
        }

        // POST: PlayLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var playList = await _context.PlayLists.FindAsync(id);
            _context.PlayLists.Remove(playList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayListExists(long id)
        {
            return _context.PlayLists.Any(e => e.Id == id);
        }
    }
}

SeeSharpersCinema.BackOffice/Controllers/TimeSlotsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeeSharpersCinema.Models;
using SeeSharpersCinema.Models.Database;
using System.Linq;
using System.Threading.Tasks;

namespace SeeSharpersCinema.BackOffice.Controllers
{
    [Authorize(Roles = "Admin,BackOffice")]
    public class TimeSlotsController : Controller
    {
        private readonly CinemaDbContext _context;

        public TimeSlotsController(CinemaDbContext context)
        {
            _context = context;
        }

        // GET: TimeSlots
        public async Task<IActionResult> Index()
        {
            var cinemaDbContext = _context.TimeSlots.Include(t => t.Room);
            return View(await cinemaDbContext.ToListAsync());
        }

        // GET: TimeSlots/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeSlot = await _context.TimeSlots
                .Include(t => t.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timeSlot == null)
            {
                return NotFound();
            }

            return View(timeSlot);
        }

        // GET: TimeSlots/Create
        public IActionResult Create()
        {
            ViewData["RoomId"] = new SelectList(_context.Rooms, "Id", "Id");
            return View();
        }

        // POST: TimeSlots/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SlotStart,SlotEnd,RoomId")] TimeSlot timeSlot)
        {
            if (ModelState.IsValid)
            {
                _context.Add(timeSlot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoomId"] = new SelectList(_context.Rooms, "Id", "Id", timeSlot.RoomId);
            return View(timeSlot);
        }

        // GET: TimeSlots/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeSlot = await _context.TimeSlots.FindAsync(id);
            if (timeSlot == null)
            {
                return NotFound();
            }
            ViewData["RoomId"] = new SelectList(_context.Rooms, "Id", "Id", timeSlot.RoomId);
            return View(timeSlot);
        }

        // POST: TimeSlots/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,SlotStart,SlotEnd,RoomId")] TimeSlot timeSlot)
        {
            if (id != timeSlot.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(timeSlot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimeSlotExists(timeSlot.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoomId"] = new SelectList(_context.Rooms, "Id", "Id", timeSlot.RoomId);
            return View(timeSlot);
        }

        // GET: TimeSlots/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeSlot = await _context.TimeSlots
                .Include(t => t.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timeSlot == null)
            {
                return NotFound();
            }

            return View(timeSlot);
        }

        // POST: TimeSlots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var timeSlot = await _context.TimeSlots.FindAsync(id);
            _context.TimeSlots.Remove(timeSlot);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimeSlotExists(long id)
        {
            return _context.TimeSlots.Any(e => e.Id == id);
        }
    }
}

SeeSharpersCinema.BackOffice/Views/TimeSlots/Create.cshtml
@model SeeSharpersCinema.Models.TimeSlot

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TimeSlot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SlotStart" class="control-label"></label>
                <input asp-for="SlotStart" class="form-control" />
                <span asp-validation-for="SlotStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SlotEnd" class="control-label"></label>
                <input asp-for="SlotEnd" class="form-control" />
                <span asp-validation-for="SlotEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <select asp-for="RoomId" class ="form-control" asp-items="ViewBag.RoomId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SeeSharpersCinema.BackOffice/Views/TimeSlots/Delete.cshtml
@model SeeSharpersCinema.Models.TimeSlot

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TimeSlot</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SlotStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SlotStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SlotEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SlotEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SeeSharpersCinema.BackOffice/Views/TimeSlots/Details.cshtml
@model SeeSharpersCinema.Models.TimeSlot

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TimeSlot</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SlotStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SlotStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SlotEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SlotEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SeeSharpersCinema.BackOffice/Views/TimeSlots/Edit.cshtml
@model SeeSharpersCinema.Models.TimeSlot

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TimeSlot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SlotStart" class="control-label"></label>
                <input asp-for="SlotStart" class="form-control" />
                <span asp-validation-for="SlotStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SlotEnd" class="control-label"></label>
                <input asp-for="SlotEnd" class="form-control" />
                <span asp-validation-for="SlotEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <select asp-for="RoomId" class="form-control" asp-items="ViewBag.RoomId"></select>
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SeeSharpersCinema.BackOffice/Views/TimeSlots/Index.cshtml
@model IEnumerable<SeeSharpersCinema.Models.TimeSlot>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Tijdslot toevoegen</a>
    <a class="btn btn-secondary" asp-controller="PlayLists" asp-action="index">Voorstellingen beheren</a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SlotStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SlotEnd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SlotStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SlotEnd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room.Id)
            </td>
            <td>

                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Bewerken</a>
                <a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.Id">Details</a>
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Verwijderen</a>
            </td>
        </tr>
}
    </tbody>
</table>