SeeSharpersCinema.Touchscreen/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SeeSharpersCinema.Models.ViewModel;
using System.Diagnostics;

namespace SeeSharpersCinema.TouchScreen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        /// <summary>
        /// HomeController constructor
        /// </summary>
        /// <param name="logger">Constructor needs a Ilogger<HomeController> object</param>
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// Get the view Index
        /// </summary>
        /// <returns>Redirect action to view Overview from controller PlayList</returns>
        public IActionResult Index()
        {
            return RedirectToAction("Overview", "Playlist");
        }

        /// <summary>
        /// Get the view Error
        /// </summary>
        /// <returns>A view with errormessages</returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SeeSharpersCinema.Touchscreen/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using SeeSharpersCinema.Models.Repository;
using SeeSharpersCinema.Models.ViewModel;
using System.Linq;

namespace SeeSharpersCinema.TouchScreen.Controllers
{
    public class MoviesController : Controller
    {
        private IMovieRepository repository;

        /// <summary>
        /// MoviesController constructor
        /// </summary>
        /// <param name="repo">Constructor needs an IMovieRepository object</param>
        public MoviesController(IMovieRepository repo)
        {
            repository = repo;
        }

        /// <summary>
        /// Gete the view Overview
        /// </summary>
        /// <returns>A view with all the movies from the repository ordered by id</returns>
        public ViewResult Overview()
            => View(new MovieListViewModel
            {
                Movies = repository.Movies
                .OrderBy(p => p.Id)
            });
    }
}

SeeSharpersCinema.Touchscreen/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SeeSharpersCinema.Models.Repository;
using System.Threading.Tasks;

namespace SeeSharpersCinema.TouchScreen.Controllers
{
    public class PaymentController : Controller
    {
        private IMovieRepository repository;

        /// <summary>
        /// PaymentController constructor
        /// </summary>
        /// <param name="repository">Constructor needs IMovieRepository object</param>
        public PaymentController(IMovieRepository repository)
        {
            this.repository = repository;
        }

        /// <summary>
        /// Get the view Index
        /// </summary>
        /// <param name="movieId">Method needs a parameter of type long</param>
        /// <returns>Ticket view of a specific movie by its id</returns>
        [Route("Ticket/Selector/Payment")]
        public async Task<IActionResult> IndexAsync(long movieId)
        {
            if (movieId == 0)
            {
                return NotFound();
            }

            var movie = await repository.Movies.FirstOrDefaultAsync(m => m.Id == movieId);

            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        /// <summary>
        /// Get the view Pay and call the email_send method of Emailservice class to send a QR code
        /// </summary>
        /// <returns>A redirect action to the view Overview from the PlayList controller</returns>
        public IActionResult Pay()
        {
            SeeSharpersCinema.Models.EmailService emailService = new SeeSharpersCinema.Models.EmailService();
            emailService.email_send();
            return RedirectToAction("Overview", "Playlist");
        }
    }
}

SeeSharpersCinema.Touchscreen/Controllers/PlayListController.cs
using Microsoft.AspNetCore.Mvc;
using SeeSharpersCinema.Models.Repository;
using System.Threading.Tasks;

namespace SeeSharpersCinema.TouchScreen.Controllers
{
    public class PlayListController : Controller
    {
        private IPlayListRepository repository;

        /// <summary>
        /// PlayListController constructor
        /// </summary>
        /// <param name="repo">Constructor needs an IPlayListRepository object</param>
        public PlayListController(IPlayListRepository repo)
        {
            repository = repo;
        }

        /// <summary>
        /// Get the view Overview in a task for correct threading in the background
        /// </summary>
        /// <returns>Movie view with all movies from the repository</returns>
        public async Task<IActionResult> Overview()
        {
            return View(await repository.FindAllAsync());
        }
    }
}

SeeSharpersCinema.Touchscreen/Controllers/SeatController.cs
using Microsoft.AspNetCore.Mvc;
using SeeSharpersCinema.Models.Order;
using SeeSharpersCinema.Models.Repository;
using System.Linq;

namespace SeeSharpersCinema.TouchScreen.Controllers
{
    public class SeatController : Controller
    {
        private IMovieRepository repository;

        /// <summary>
        /// SeatController constructor
        /// </summary>
        /// <param name="repository">Constructor needs an IMovieRepository object</param>
        public SeatController(IMovieRepository repository)
        {
            this.repository = repository;
        }

        /// <summary>
        /// Get the view Selector
        /// </summary>
        /// <param name="movieId">Method needs a parameter of type long</param>
        /// <returns>Seat view of a specific movie by its id</returns>
        [Route("Seat/Selector/{movieId}")]
        public IActionResult Selector([FromRoute] long movieId)
        {
            var selectedMovie = repository.Movies.FirstOrDefault(m => m.Id == movieId);
            if (selectedMovie == null)
            {
                return NotFound();
            }

            Ticket ticket = new Ticket()
            {
                Movie = selectedMovie
            };
            return View(ticket);
        }
    }
}

SeeSharpersCinema.Touchscreen/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using SeeSharpersCinema.Models.Order;
using SeeSharpersCinema.Models.Repository;
using System.Linq;

namespace SeeSharpersCinema.TouchScreen.Controllers
{
    public class TicketController : Controller
    {

        private IMovieRepository repository;

        /// <summary>
        /// TicketController constructor
        /// </summary>
        /// <param name="repository">Constructor needs an IMovieRepository object</param>
        public TicketController(IMovieRepository repository)
        {
            this.repository = repository;
        }

        /// <summary>
        /// Get the view Options
        /// </summary>
        /// <param name="movieId">Method needs a parameter of type long</param>
        /// <returns>Ticket view of a specific movie by its id</returns>
        [Route("Ticket/Options/{movieId}")]
        public IActionResult Options([FromRoute] long movieId)
        {
            var selectedMovie = repository.Movies.FirstOrDefault(m => m.Id == movieId);
            if (selectedMovie == null)
            {
                return NotFound();
            }

            Ticket ticket = new Ticket()
            {
                Movie = selectedMovie
            };
            return View(ticket);
        }

        /// <summary>
        /// Get the view QR
        /// </summary>
        /// <param name="ticket">Method needs a Ticket object</param>
        /// <returns>Ticket view of a specific ticket object</returns>
        [Route("Ticket/QR/{TicketId}")]
        public IActionResult QR(Ticket ticket)
        {
            return View(ticket);
        }
    }
}

SeeSharpersCinema.Touchscreen/Views/PlayList/Overview.cshtml
@model IEnumerable<PlayList>
@{ ViewData["Title"] = "Overview"; }

<div class="row">
    <h1>Nu en Straks!</h1>
</div>

<div class="row">
    
    @foreach (var item in Model)
    {
        <div class="col-2">
            <div class="card card-outline-primary m-1 p-1">
                <div class="card-text p-1">
                    <a asp-controller="Seat" asp-action="Selector" asp-route-movieId="@item.MovieId">
                        <img src="@item.Movie.PosterUrl" class="img-fluid" />
                        <p>@item.TimeSlot.SlotStart.ToString("MM-dd-yyyy HH:mm")</p>
                        <p>Zaal @item.TimeSlot.RoomId</p> 
                    </a>
                </div>
            </div>
        </div>
    }
</div>

SeeSharpersCinema.Touchscreen/Views/Seat/Selector.cshtml
@model Ticket

<a asp-controller="playlist" asp-action="Overview" type="button" class="btn btn-primary btn-lg">Back</a>
<h1>Stoel selectie</h1>
<h2>@Model.Movie.Title</h2>
<img class="img-fluid" src="@Model.Movie.PosterUrl" />
<ul>
    <li>@Model.Movie.Technique</li>
    <li>@Model.Movie.Duration Min</li>
    <li>Director: @Model.Movie.Director</li>
    <li>Opgenomen: @Model.Movie.Country</li>
    <li>Genre: @Model.Movie.Genre</li>
    <li>Taal: @Model.Movie.Language</li>
    <li>Jaar: @Model.Movie.Year</li>
    <li>Kijkwijzer: @Model.Movie.ViewIndication</li>
    <li>@Model.Movie.Description</li>
</ul>
<h3>Filmprijs: € @(Model.Movie.IsLongMovie ? Model.Movie.LongMovieAddition + Model.Movie.BasePrice : Model.Movie.BasePrice )</h3>
<a asp-controller="Ticket" asp-action="Options" asp-route-movieId="@Model.Movie.Id" class="btn btn-primary btn-lg">To payment overview</a>

SeeSharpersCinema.Touchscreen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SeeSharpersCinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>